sudo: required
services:
 - docker

before_install:
 - docker build -t ealhajsalem/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true ealhajsalem/docker-react npm run test

language: generic

deploy:
 provider: elasticbeanstalk
 access_key_id: $access_key_id
 secret_access_key: "$secret_access_key"
 region: "us-east-1"
 app: docker
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-us-east-1-411777220940"
 bucket_path: "docker"
   